In [1]:
from keras.datasets import imdb

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words = 10000)

Using TensorFlow backend.


In [2]:
print(train_data.ndim)

1


In [3]:
word_index = imdb.get_word_index()
reverse_word_index = dict(
        [(value, key) for (key, value) in word_index.items()])
decoded_review = ' '.join(
        [reverse_word_index.get(i - 3, '?') for i in train_data[0]])

In [4]:
import numpy as np 
def vectorize_sequence(sequences, dimension = 10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.
        return results
    
x_train = vectorize_sequence(train_data)
x_test = vectorize_sequence(test_data)


In [5]:
print(x_train)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
y_train = np.asarray(train_labels).astype('float32')
y_test = np.asarray(test_labels).astype('float32')

In [7]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(16, activation = 'relu', input_shape = (10000,)))
model.add(layers.Dense(16, activation = 'relu'))
model.add(layers.Dense(1,  activation = 'sigmoid'))

In [8]:
model.compile(optimizer = 'rmsprop', 
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

In [9]:
from keras import optimizers
model.compile(optimizer = optimizers.RMSprop(lr=0.001),
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

In [10]:
from keras import losses
from keras import metrics

model.compile(optimizer = optimizers.RMSprop(lr = 0.001),
              loss = losses.binary_crossentropy,
              metrics = [metrics.binary_accuracy])

In [11]:
#Setting aside the first 10000 data entries to use for training validation

x_val = x_train[:10000]
partial_x_train = x_train[10000:]
y_val = y_train[:10000]
partial_y_train = y_train[10000:]

In [12]:
#Now to finally train the model

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['acc'])

history = model.fit(partial_x_train,
                    partial_y_train,
                    epochs = 20,
                    batch_size = 512,
                    validation_data = (x_val, y_val))

Train on 15000 samples, validate on 10000 samples
Epoch 1/20
15000/15000 [==============================] - 5s 366us/step - loss: 0.6932 - acc: 0.4982 - val_loss: 0.6932 - val_acc: 0.4947
Epoch 2/20
15000/15000 [==============================] - 2s 131us/step - loss: 0.6931 - acc: 0.5035 - val_loss: 0.6932 - val_acc: 0.4947
Epoch 3/20
15000/15000 [==============================] - 2s 129us/step - loss: 0.6931 - acc: 0.5035 - val_loss: 0.6932 - val_acc: 0.4947
Epoch 4/20
15000/15000 [==============================] - 2s 129us/step - loss: 0.6931 - acc: 0.5035 - val_loss: 0.6932 - val_acc: 0.4947
Epoch 5/20
15000/15000 [==============================] - 2s 128us/step - loss: 0.6931 - acc: 0.5035 - val_loss: 0.6932 - val_acc: 0.4947
Epoch 6/20
15000/15000 [==============================] - 3s 202us/step - loss: 0.6931 - acc: 0.5035 - val_loss: 0.6933 - val_acc: 0.4947
Epoch 7/20
15000/15000 [==============================] - 2s 143us/step - loss: 0.6931 - acc: 0.5035 - val_loss: 0.6932 - 

In [13]:
model = models.Sequential()
model.add(layers.Dense(16, activation = 'relu', input_shape = (10000,)))
model.add(layers.Dense(16, activation = 'relu'))
model.add(layers.Dense(16, activation = 'relu'))
model.add(layers.Dense(16, activation = 'relu'))
model.add(layers.Dense(1,  activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(x_train, y_train, epochs = 20, batch_size = 512)
results = model.evaluate(x_test, y_test)
print (results)

Epoch 1/20
25000/25000 [==============================] - 4s 171us/step - loss: 0.6932 - acc: 0.4964 4 - ETA: 0s - loss: 0.6932 - acc:
Epoch 2/20
25000/25000 [==============================] - 5s 197us/step - loss: 0.6932 - acc: 0.4941
Epoch 3/20
25000/25000 [==============================] - 4s 161us/step - loss: 0.6932 - acc: 0.4950
Epoch 4/20
25000/25000 [==============================] - 3s 104us/step - loss: 0.6932 - acc: 0.5015
Epoch 5/20
25000/25000 [==============================] - 3s 106us/step - loss: 0.6932 - acc: 0.4989
Epoch 6/20
25000/25000 [==============================] - 6s 254us/step - loss: 0.6932 - acc: 0.4996
Epoch 7/20
25000/25000 [==============================] - 3s 125us/step - loss: 0.6932 - acc: 0.4979
Epoch 8/20
25000/25000 [==============================] - 3s 103us/step - loss: 0.6932 - acc: 0.4987 2s - 
Epoch 9/20
25000/25000 [==============================] - 2s 78us/step - loss: 0.6932 - acc: 0.4996
Epoch 10/20
25000/25000 [===========================

In [14]:
model.predict(x_test)

array([[0.58491015],
       [0.5015781 ],
       [0.5015781 ],
       ...,
       [0.5015781 ],
       [0.5015781 ],
       [0.5015781 ]], dtype=float32)